package ads.set2.knapsack;

import java.util.ArrayList;
import java.util.Collection;

/**
 * A packing of a knapsack. A packing is specified by a list of items to be
 * packed and the profit generated by packing them. To use this class, create a
 * new instance, call {@link #setProfit(int)} to set the profit, and call
 * {@link #getItems()} to obtain the list of items in this packing and add items
 * to it.
 */
public class Packing {

	/** The items in this packing. */
	private Collection<Item> items = new ArrayList<>();
	/** Profit generated by this packing. */
	private int profit = 0;

	/**
	 * Returns the profit generated by this packing.
	 */
	public int getProfit() {
		return profit;
	}

	/**
	 * Sets the profit generated by this packing.
	 * 
	 * @throws IllegalArgumentException
	 *             if {@code profit < 0}.
	 */
	public void setProfit(final int profit) {
		if (profit < 0) {
			throw new IllegalArgumentException("profit cannot be negative.");
		}
		this.profit = profit;
	}

	/**
	 * Returns the list of items in this packing. The returned list can be
	 * modified to add more items.
	 */
	public Collection<Item> getItems() {
		return items;
	}

}
